# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BUILD_SOURCE_DIRS "/home/simbricks/COSSIM/cCERTI;/home/simbricks/COSSIM/cCERTI")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake-3.22/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "CERTI built using CMake")
set(CPACK_GENERATOR "TGZ;ZIP")
set(CPACK_IGNORE_FILES "/\\.pydev.*;/\\.settings/;/CVS/;/\\.svn/;\\.swp$;\\.#;/#;.*~;cscope.*;\\.cproject;\\.project;autom4te.cache/*;\\.git")
set(CPACK_INSTALLED_DIRECTORIES "/home/simbricks/COSSIM/cCERTI;/")
set(CPACK_INSTALL_CMAKE_PROJECTS "")
set(CPACK_INSTALL_PREFIX "/home/simbricks/COSSIM/cCERTI/build_certi")
set(CPACK_MODULE_PATH "/home/simbricks/COSSIM/cCERTI/scripts")
set(CPACK_NSIS_DISPLAY_NAME "CERTI 4.0.0")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "CERTI 4.0.0")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OUTPUT_CONFIG_FILE "/home/simbricks/COSSIM/cCERTI/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "CERTI Development Team <certi-devel@nongnu.org>")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/home/simbricks/COSSIM/cCERTI/CERTI_DESCRIPTION.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "CERTI An efficient Open Source HLA RunTime Infrastructure")
set(CPACK_PACKAGE_FILE_NAME "CERTI-4.0.0-Source")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "CERTI 4.0.0")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "CERTI 4.0.0")
set(CPACK_PACKAGE_NAME "CERTI")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "ONERA/DTIM")
set(CPACK_PACKAGE_VERSION "4.0.0")
set(CPACK_PACKAGE_VERSION_MAJOR "4")
set(CPACK_PACKAGE_VERSION_MINOR "0")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_PROJECT_CONFIG_FILE "/home/simbricks/COSSIM/cCERTI/CERTICPackOptions.cmake")
set(CPACK_RESOURCE_FILE_LICENSE "/home/simbricks/COSSIM/cCERTI/COPYING.txt")
set(CPACK_RESOURCE_FILE_README "/usr/share/cmake-3.22/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake-3.22/Templates/CPack.GenericWelcome.txt")
set(CPACK_RPM_PACKAGE_LICENSE "GPLv2 and LGPLv2")
set(CPACK_RPM_PACKAGE_RELOCATABLE "TRUE")
set(CPACK_RPM_PACKAGE_SOURCES "ON")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TGZ;ZIP")
set(CPACK_SOURCE_IGNORE_FILES "/\\.pydev.*;/\\.settings/;/CVS/;/\\.svn/;\\.swp$;\\.#;/#;.*~;cscope.*;\\.cproject;\\.project;autom4te.cache/*;\\.git")
set(CPACK_SOURCE_INSTALLED_DIRECTORIES "/home/simbricks/COSSIM/cCERTI;/")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/simbricks/COSSIM/cCERTI/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "CERTI-4.0.0-Source")
set(CPACK_SOURCE_TOPLEVEL_TAG "Linux-Ubuntu_22.04-x86_64-Source")
set(CPACK_STRIP_FILES "")
set(CPACK_SYSTEM_NAME "Linux-Ubuntu_22.04-x86_64")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Linux-Ubuntu_22.04-x86_64-Source")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/simbricks/COSSIM/cCERTI/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
